/// Flutter icons MamaFitClub
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MamaFitClub
///      fonts:
///       - asset: fonts/MamaFitClub.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MamaFitClub';

  static const IconData stretch = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bookings = const IconData(0xe801, fontFamily: _kFontFam);
}
